apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-app
  labels:
    app: harness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-app
  template:
    metadata:
      labels:
        app: harness-app
    spec:
      containers:
        - name: harness-app
          image: {{.Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
